Add retry loop around failed attempts to read stats
We stopped collected for min*biox due to a transient DNS failure:
2018-01-12T17:50:39-08:00 main.go:183 ERROR Failed to retrieve stats for
cluster "minvmbiox": Get https://minvmbiox.west.isilon.com:8080/platform/1/statistics/current?degraded=true&devid=all&key=node.clientstats.connected.hdfs&...
: dial tcp: lookup minvmbiox.west.isilon.com on 10.7.190.7:53: read udp 10.7.223.174:42567->10.7.190.7:53: i/o timeout